# Generated by Django 3.2.6 on 2021-08-18 20:57

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_blockeduser_blockeduserhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
